name: Send DaddyLive Schedule to Discord

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:        # allow manual run

jobs:
  send-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Discord webhook secret
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "❌ ERROR: Discord webhook secret (DISCORD_WEBHOOK) is missing."
            exit 1
          else
            echo "✅ Discord webhook secret found."
          fi

      - name: Fetch DaddyLive schedule
        run: |
          echo "📥 Downloading schedule JSON..."
          curl -sL "https://daddylivestream.com/schedule/schedule-generated.php" -o schedule.json
          if [ ! -s schedule.json ]; then
            echo "❌ ERROR: Failed to download schedule.json (file is empty or missing)."
            exit 1
          else
            echo "✅ schedule.json downloaded successfully."
          fi

      - name: Send schedule to Discord
        run: |
          echo "📤 Sending schedule.json to Discord..."
          curl -H "Content-Type: application/json" \
               -X POST \
               -d @"schedule.json" \
               "${{ secrets.DISCORD_WEBHOOK }}"
