name: Send DaddyLive Schedule to Discord

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:

jobs:
  send-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Discord webhook secret
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "❌ ERROR: Discord webhook secret (DISCORD_WEBHOOK) is missing."
            exit 1
          fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch DaddyLive schedule
        run: |
          curl -sL "https://daddylivestream.com/schedule/schedule-generated.php" -o schedule.json
          if [ ! -s schedule.json ]; then
            echo "❌ ERROR: Failed to download schedule.json (file is empty)."
            exit 1
          fi

      - name: Build Discord embed payload
        run: |
          # Build fields for each day
          FIELDS=$(jq -c '
            to_entries |
            map({
              name: .key,
              value: (
                .value["TV Shows"] |
                map("\(.time) - \(.event) | Channels: \(.channels | join(", "))") |
                join("\n")
              ),
              inline: false
            })
          ' schedule.json)

          # Wrap fields in embeds JSON
          echo "{\"username\": \"DaddyLive Schedule\", \"embeds\": [{\"title\": \"Upcoming Events\", \"color\": 5814783, \"fields\": $FIELDS}]}" > discord_payload.json
          cat discord_payload.json

      - name: Send schedule to Discord
        run: |
          curl -v -H "Content-Type: application/json" \
               -X POST \
               -d @discord_payload.json \
               "${{ secrets.DISCORD_WEBHOOK }}"
