name: Send DaddyLive Schedule to Discord

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:

jobs:
  send-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Discord webhook secret
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "❌ ERROR: Discord webhook secret (DISCORD_WEBHOOK) is missing."
            exit 1
          fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch schedule from GitHub with retries
        run: |
          MAX_RETRIES=25
          COUNT=0
          STATUS=0
          while [ $COUNT -lt $MAX_RETRIES ]; do
            STATUS=$(curl -s -o schedule.json -w "%{http_code}" "https://raw.githubusercontent.com/DisabledAbel/daddylivehd-m3u/main/schedule.json")
            if [ "$STATUS" -eq 200 ] && [ -s schedule.json ]; then
              echo "✅ schedule.json fetched successfully on attempt $((COUNT+1))"
              break
            fi
            COUNT=$((COUNT+1))
            echo "⚠️ Attempt $COUNT failed (HTTP $STATUS). Retrying in 5 seconds..."
            sleep 5
          done

          if [ "$STATUS" -ne 200 ] || [ ! -s schedule.json ]; then
            echo "❌ Failed to fetch schedule after $MAX_RETRIES attempts."

            # Send red error embed to Discord
            SEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" \
                 -X POST \
                 -d "{
                       \"username\": \"DaddyLive Schedule\",
                       \"embeds\": [
                         {
                           \"title\": \"⚠️ ERROR: Schedule Fetch Failed\",
                           \"description\": \"Failed to fetch schedule.json from GitHub after $MAX_RETRIES attempts. Last HTTP status $STATUS.\",
                           \"color\": 16711680
                         }
                       ]
                     }" \
                 "${{ secrets.DISCORD_WEBHOOK }}")

            if [ "$SEND_STATUS" -eq 204 ]; then
              echo "✅ Error embed successfully sent to Discord."
            else
              echo "❌ Failed to send error embed to Discord. HTTP status $SEND_STATUS"
            fi

            exit 1
          fi

      - name: Build Discord embed payload
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          FIELDS=$(jq -c '
            to_entries |
            map({
              name: .key,
              value: (
                .value["TV Shows"] |
                map("\(.time) - \(.event) | Channels: \(.channels | join(", "))") |
                join("\n")
              ),
              inline: false
            })
          ' schedule.json)

          echo "{\"username\": \"DaddyLive Schedule\", \"embeds\": [{\"title\": \"✅ Upcoming Events\", \"color\": 65280, \"fields\": $FIELDS, \"timestamp\": \"$TIMESTAMP\", \"footer\": {\"text\": \"Updated by GitHub Actions\"}}]}" > discord_payload.json
          cat discord_payload.json

      - name: Send schedule to Discord
        run: |
          SEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" \
               -X POST \
               -d @discord_payload.json \
               "${{ secrets.DISCORD_WEBHOOK }}")

          if [ "$SEND_STATUS" -eq 204 ]; then
            echo "✅ Schedule successfully sent to Discord."
          else
            echo "❌ Failed to send schedule to Discord. HTTP status $SEND_STATUS"
            exit 1
