name: Update Playlist

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  fetch_m3u8_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          success=false
          for i in {1..3}; do
            echo "Attempt $i..."
            if npm install; then
              echo "✅ Success on attempt $i"
              success=true
              break
            fi
            echo "❌ Failed npm install. Retrying in 10s..."
            sleep 10
          done

          if [ "$success" = false ]; then
            echo "❌ npm install failed after 3 attempts."
            exit 1
          fi

      - name: Get channels
        run: |
          success=false
          for i in {1..10}; do
            echo "Attempt $i..."
            if node generate-playlist.js; then
              echo "✅ Success on attempt $i"
              success=true
              break
            fi
            echo "❌ Failed (exit code $?). Retrying in 15s..."
            sleep 15
          done

          if [ "$success" = false ]; then
            echo "❌ All 10 attempts failed. Exiting."
            exit 1
          fi

      - name: Merge playlists
        run: |
          success=false
          for i in {1..5}; do
            echo "Attempt $i..."
            if node merge.js; then
              echo "✅ Success on attempt $i"
              success=true
              break
            fi
            echo "❌ Failed merging playlists. Retrying in 10s..."
            sleep 10
          done

          if [ "$success" = false ]; then
            echo "❌ merge.js failed after 5 attempts."
            exit 1
          fi

      - name: Update README
        run: |
          success=false
          for i in {1..3}; do
            echo "Attempt $i..."
            if node update-readme.js; then
              echo "✅ Success on attempt $i"
              success=true
              break
            fi
            echo "❌ Failed updating README. Retrying in 10s..."
            sleep 10
          done

          if [ "$success" = false ]; then
            echo "❌ update-readme.js failed after 3 attempts."
            exit 1
          fi

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff-index --quiet HEAD; then
            echo "✅ No changes to commit"
          else
            git commit -m "🔄 Auto-update playlist"
            git push
          fi

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"✅ Playlist update succeeded on $(date).\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"❌ Playlist update FAILED on $(date). Check Actions logs.\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
