
on:
  push:
    branches:
      - main

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Ensure directories exist
      - name: Ensure directories
        run: |
          mkdir -p output backups  # 'output' for main playlist, 'backups' for per-channel backups

      # 4. Run the M3U update script with backup logic
      - name: Run M3U Update Script
        run: |
          SCRIPT_PATH=".github/scripts/update_m3u.py"  # Replace with your actual script path
          if [ -f "$SCRIPT_PATH" ]; then
            python3 "$SCRIPT_PATH"
          else
            echo "$SCRIPT_PATH not found!"
            exit 1
          fi

          # Example backup logic (if your script doesn't already do it)
          if [ -f "playlist.m3u" ]; then
            cp playlist.m3u backups/playlist_backup_$(date +%Y%m%d%H%M%S).m3u
            echo "Backup created in backups/ folder"
          fi

      # 5. Commit main playlist and backups
      - name: Commit and push updated M3U
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add playlist.m3u backups/*.m3u || echo "No M3U files to add"

          git diff --cached --quiet || git commit -m "Update playlist.m3u and backups after merge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
