name: Sync & Update Playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *' # every 3 hours

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v3

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/pigzillaaa/daddylive.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories -m "Merge upstream playlists"

      - name: Commit updated playlists
        run: |
          # Configure git user
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Only commit if there are changes
          if git ls-files '*.m3u' | grep .; then
            git add '*.m3u'
            if ! git diff --cached --quiet; then
              git commit -m "Update playlists"
              git push
            else
              echo "No changes to commit."
            fi
          else
            echo "No .m3u files found, skipping commit."
          i
