name: Update M3U after Merge

# Trigger after any push to main (this includes PR merges)
on:
  push:
    branches:
      - main

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Run your playlist update script
      - name: Run M3U Update Script
        run: |
          python3 update_m3u.py

      # 4. Commit changes back to repo
      - name: Commit and push updated M3U
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Update playlist.m3u after merge" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
