name: Merge Playlists

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Merge playlists
        run: |
          set -euo pipefail
          echo "#EXTM3U" > daddylive-merged.m3u8
          for f in *.m3u *.m3u8; do
            if [ "$f" != "daddylive-merged.m3u8" ]; then
              tail -n +2 "$f" >> daddylive-merged.m3u8 || true
            fi
          done

      - name: Fix M3U formatting
        run: |
          python3 <<'PY'
import re, pathlib
path = pathlib.Path("daddylive-merged.m3u8")
lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
fixed = ["#EXTM3U"]
for i, line in enumerate(lines):
    if line.startswith("#EXTINF:"):
        fixed.append(line)
        if i + 1 < len(lines) and lines[i+1].startswith("http"):
            fixed.append(lines[i+1])
path.write_text("\n".join(fixed) + "\n", encoding="utf-8")
PY

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daddylive-merged.m3u8
          git diff --cached --quiet || git commit -m "Update merged M3U"
          git push
