name: Merge Playlists

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # every hour

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests

      # --- OpenRouter key check (safe) ---
      - name: Test OpenRouter key (quick curl HEAD)
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          if curl -sSf -I -H "Authorization: Bearer $OPENROUTER_API_KEY" "https://api.openrouter.ai/v1/models" >/dev/null 2>&1; then
            echo "Key OK"
          else
            echo "Key failed"
            exit 1
          fi

      - name: Functional OpenRouter test (Python, safe output)
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          python3 - <<'PY'
import os, sys, requests
key = os.environ.get("OPENROUTER_API_KEY")
if not key:
    print("No key in env"); sys.exit(2)

headers = {"Authorization": f"Bearer {key}", "Content-Type": "application/json"}
body = {"model": "gpt-4o-mini", "messages": [{"role":"user","content":"Say 'hello' in one sentence."}]}

try:
    r = requests.post("https://api.openrouter.ai/v1/chat/completions", json=body, headers=headers, timeout=15)
    if r.ok:
        print("API OK — response snippet:")
        print(r.text[:300].replace("\\n"," "))
    else:
        print(f"API returned status {r.status_code}")
        sys.exit(1)
except Exception as e:
    print("Request error:", e)
    sys.exit(1)
PY

      # --- Your playlist merging logic ---
      - name: Merge playlists
        run: |
          set -e
          echo "#EXTM3U" > daddylive-merged.m3u8
          cat playlist1.m3u playlist2.m3u >> daddylive-merged.m3u8
          # remove duplicate EXTM3U headers
          sed -i '2,${/^#EXTM3U$/d}' daddylive-merged.m3u8

      - name: Commit merged file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daddylive-merged.m3u8
          git commit -m "Update merged playlist" || echo "No changes"
          git push
