name: Sync & Update Playlists

on:
  workflow_dispatch:
  push:
    paths:
      - 'README.md'
  schedule:
    - cron: "0 */3 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add upstream and merge
        run: |
          git remote add upstream https://github.com/pigzillaaa/daddylive.git || true
          git fetch upstream || true
          git merge upstream/main --allow-unrelated-histories || true

      - name: Merge playlists (main + events) and create per-channel backups
        run: |
          set -euo pipefail

          main_path="playlist.m3u"
          events_path="events.m3u"

          rm -f "$main_path" "$events_path"
          touch "$main_path" "$events_path"

          shopt -s nullglob
          files=( *.m3u )
          shopt -u nullglob

          newfiles=()
          for f in "${files[@]:-}"; do
            if [ "$f" != "$main_path" ] && [ "$f" != "$events_path" ]; then
              newfiles+=( "$f" )
            fi
          done

          if [ ${#newfiles[@]} -gt 0 ]; then
            for f in "${newfiles[@]}"; do
              if [[ "$f" == *events* ]]; then
                cat "$f" >> "$events_path"
              else
                cat "$f" >> "$main_path"
              fi
            done
          else
