# Example workflow with authentication fix
name: Update M3U

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required for pushing changes
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Set up authentication
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        
    # Your existing workflow steps here
    - name: Update M3U files
      run: |
        # Your update script/commands
        echo "Running update commands..."
        
    - name: Commit and push changes
      run: |
        git add .
        git diff --staged --quiet || git commit -m "Update M3U files - $(date)"
        git push origin main

- name: Fork Sync
  uses: tgymnich/fork-sync@v2.0.10
