      - name: Merge playlists (add per-channel backups)
        run: |
          set -e
          python3 <<'PY'
import sys
from pathlib import Path

main_path = Path("playlist.m3u")
backup_path = Path("backup.m3u")
out_path = main_path

def parse_entries(lines):
    entries = []
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i].rstrip("\n")
        if line.startswith("#EXTINF"):
            extinf = line
            j = i + 1
            url = ""
            # skip blank/comment lines
            while j < n and (lines[j].strip() == "" or lines[j].startswith("#")):
                j += 1
            if j < n:
                url = lines[j].strip()
                i = j + 1
            else:
                i = j
            entries.append((extinf, url))
        else:
            i += 1
    return entries

def extract_name(extinf_line):
    if ',' in extinf_line:
        return extinf_line.split(',', 1)[1].strip().lower()
    return extinf_line.strip().lower()

if not main_path.exists():
    print("No playlist.m3u found in repo. Nothing to merge into.")
    sys.exit(0)

main_lines = main_path.read_text(encoding="utf-8").splitlines()
backup_lines = backup_path.read_text(encoding="utf-8").splitlines() if backup_path.exists() else []

header_lines = []
idx = 0
while idx < len(main_lines) and not main_lines[idx].startswith("#EXTINF"):
    header_lines.append(main_lines[idx])
    idx += 1

main_entries = parse_entries(main_lines)
backup_entries = parse_entries(backup_lines)

backup_map = {}
for extinf, url in backup_entries:
    name = extract_name(extinf)
    if name and url:
        if name not in backup_map:
            backup_map[name] = url

out_lines = []
out_lines.extend(header_lines)
for extinf, url in main_entries:
    out_lines.append(extinf)
    if url:
        out_lines.append(url)
    name = extract_name(extinf)
    b_url = backup_map.get(name)
    if b_url and b_url.strip() and b_url.strip() != (url or "").strip():
        out_lines.append(b_url)

out_path.write_text("\n".join(out_lines) + ("\n" if out_lines else ""), encoding="utf-8")
print("✅ Merged per-channel backups. Wrote", str(out_path))
PY
