name: Sync & Update Playlists

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"  # every 3 hours

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add upstream and merge
        run: |
          git remote add upstream https://github.com/pigzillaaa/daddylive.git || true
          git fetch upstream || true
          git merge upstream/main --allow-unrelated-histories || true

      - name: Merge playlists and create per-channel backups
        run: |
          set -euo pipefail

          rm -f "$main_path"
          touch "$main_path"

          # collect .m3u files except the main one
          shopt -s nullglob
          files=( *.m3u )
          shopt -u nullglob

          # remove playlist.m3u from list if present
          newfiles=()
          for f in "${files[@]:-}"; do
            if [ "$f" != "$main_path" ]; then
              newfiles+=( "$f" )
            fi
          done

          # merge into playlist.m3u (or write header if none)
          if [ ${#newfiles[@]} -gt 0 ]; then
            for f in "${newfiles[@]}"; do
              cat "$f" >> "$main_path"
            done
          else
            printf '%s\n' "#EXTM3U" > "$main_path"
          fi

          # create channels/ directory
          mkdir -p channels

          # parse per-channel: group each #EXTINF and following lines into a file
          # This assumes each channel block starts with a line beginning with "#EXTINF"
          awk -v outdir=channels '
            /^#EXTINF/ {
              if (block != "") {
                fname = outdir "/" safe
                print block > fname
                close(fname)
              }
              block = $0 "\n"
              # get channel name (after last comma)
              n = split($0, arr, ",")
              name = arr[n]
              gsub(/[^A-Za-z0-9]/, "_", name)
              safe = name
              next
            }
            {
              if (block == "") next
              block = block $0 "\n"
            }
            END {
              if (block != "") {
                fname = outdir "/" safe
                print block > fname
                close(fname)
              }
            }
          ' "${newfiles[@]:-}"

      - name: Commit updated playlists
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # Add files if they exist; ignore if not (so step doesn't fail)
          git add playlist.m3u || true
          git add channels/*.m3u || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update playlists & backups"
            git push
          fi
