name: Update Playlist

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 mins
  workflow_dispatch:

permissions:
  contents: write   # allow pushing back to repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main    # ensure we’re on the right branch
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update playlist
        run: |
          set -e
          python3 scripts/update_playlist.py   # replace with your real script

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-update playlist [skip ci]" || echo "No changes to commit"
          git push origin main
