name: Auto-sync from pigzillaaa/daddylive

on:
  schedule:
    - cron: "0 */2 * * *"     # every 2 hours
  workflow_dispatch:          # manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add upstream remote
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/pigzillaaa/daddylive.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "No upstream changes to merge"

      - name: Push changes
        run: git push origin main
