name: Master Playlist Updater

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install node-fetch

      - name: Generate English-only playlist
        run: node generate-playlist.js

      - name: Merge English-only playlists
        run: node merge-playlists.js

      - name: Commit & Push playlists safely
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u merged-playlist.m3u
          
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "Update English-only playlists"
            
            # Ensure we’re on the branch that triggered the workflow
            git checkout -B ${{ github.ref_name }}
            
            # Push using GitHub token
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
