name: Update Playlist

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes, adjust as needed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install node-fetch

      - name: Generate playlist (English only)
        run: node generate-playlist.js

      - name: Commit & Push playlist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "Update English-only playlist"
            git pull --rebase origin ${{ github.ref_name }}
            git push origin HEAD:${{ github.ref_name }}
          fi
